import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import styled from '@emotion/styled';
import {Search} from '../components/search';
// STYLE - imports
import {colors} from '../public/consts'
import {breakpoints} from '../public/consts'
import { css, Global } from '@emotion/react';

const bp = breakpoints

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Search_Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/index.png" />
      </Head>
      <Global
          styles={css`
            body{
                height: 100vh;
            }
            #root{
                height:100%;
            }
            .app{
                height:100%;
            }
            #__next{
                height:100%;
            }
            `}
        />
        <Search size="big"/>
    </div>
  )
}

export default Home
